OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
EXTRAKEY_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes

#HAPTIC FEEBACK
HAPTIC_ENABLE = yes

#PER KEY RGB
RGB_MATRIX_ENABLE = yes     # Enable keyboard RGB matrix (do not use together with RGBLIGHT_ENABLE)

#AUDIO
AUDIO_ENABLE = yes
MUSIC_ENABLE = yes