#pragma once

#define PLOOPY_HOST_LED_CONTROL
#define PLOOPY_DRAGSCROLL_INVERT
#define PLOOPY_DRAGSCROLL_DIVISOR_H 25.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 20.0

#define PLOOPY_DPI_OPTIONS { 300, 550, 800, 1200 }
#define PLOOPY_DPI_DEFAULT 2