AUTO_SHIFT_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
UNICODE_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no


COMBO_ENABLE = yes

BOOTLOADER = atmel-dfu

BOOTMAGIC_ENABLE = noss
LTO_ENABLE = yes

WPM_ENABLE = yes
