#
#POINTING_DEVICE_ENABLE = yes
#POINTING_DEVICE_DRIVER =  cirque_pinnacle_i2c
#CIRQUE_PINNACLE_DIAMETER_MM = 40
#CIRQUE_PINNACLE_ATTENUATION = EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_4X
#CIRQUE_PINNACLE_POSITION_MODE = CIRQUE_PINNACLE_RELATIVE_MODE
#CIRQUE_PINNACLE_SKIP_SENSOR_CHECK
##Enable tap to “left click”. Works on both sides of a split keyboard.
#CIRQUE_PINNACLE_TAP_ENABLE
#CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
##in this mode enables side scroll. Touch originating on the right side can trigger vertical scroll (IntelliSense trackpad style).
#POINTING_DEVICE_GESTURES_SCROLL_ENABLE

#TAP_DANCE_ENABLE = yes
VIA_ENABLE = yes