// Copyright 2023 Ryan Neff (@JellyTitan)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once
/* Mouse settings */

#define POINTING_DEVICE_ROTATION_180
#define POINTING_DEVICE_TASK_THROTTLE_MS 10
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE // Circular scroll.
#define CIRQUE_PINNACLE_DIAMETER_MM 40
#define CIRQUE_PINNACLE_TAP_ENABLE
#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE
//#define CIRQUE_PINNACLE_ATTENUATION EXTREG__TRACK_ADCCONFIG__ADC_ATTENUATE_4X
//#define CIRQUE_PINNACLE_POSITION_MODE CIRQUE_PINNACLE_RELATIVE_MODE
//#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
//#define AUTO_MOUSE_DEFAULT_LAYER 4
//#define AUTO_MOUSE_TIME 650
//#define MOUSEKEY_MOVE_DELTA 8
//#define MOUSEKEY_WHEEL_MAX_SPEED 42
// #define MOUSEKEY_WHEEL_TIME_TO_MAX 15


#ifdef AUDIO_ENABLE
    #define AUDIO_PIN GP18
    #define AUDIO_PWM_DRIVER PWMD1
    #define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A

    #define AUDIO_INIT_DELAY
    #define AUDIO_ENABLE_TONE_MULTIPLEXING
    #define AUDIO_TONE_MULTIPLEXING_RATE_DEFAULT 10
    #define STARTUP_SONG SONG(TO_BOLDLY_GO)
    #define AUDIO_OFF_SONG SONG(MARIO_GAMEOVER)
    #define AUDIO_ON_SONG SONG(MARIO_THEME)
    //#define STARTUP_SONG SONG(RICK_ROLL)
    //#define STARTUP_SONG SONG(IMPERIAL_MARCH)

    #define AUDIO_VOICES
    //#define AUDIO_VOICE_DEFAULT butts_fader
#endif


