#TAP_DANCE_ENABLE = yes
VIA_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c
POINTING_DEVICE_ENABLE = yes
MOUSEKEY_ENABLE = yes
CONSOLE_ENABLE=yes					
ENCODER_ENABLE = yes 
ENCODER_MAP_ENABLE = yes 