name: Build QMK firmware

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    name: 'QMK Userspace Build'
    uses: qmk/.github/.github/workflows/qmk_userspace_build.yml@main
    with:
      qmk_repo: qmk/qmk_firmware
      qmk_ref: develop
      preparation_command: |
        find qmk_firmware -type d -path '*/keyboards/*/keymaps/via' -name 'via' -print -exec rm -rf '{}' \; -prune
